name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Hello world action
        with: # Set the secret as an input
          super_secret: ${{ secrets.MYTESTSEC }}
        env: # Or as an environment variable
          super_secret: ${{ secrets.MYTESTSEC }}
