name: second workflows

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  # This workflow contains a single job called "build"
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Hello world action
       with: # Set the secret as an input
        super_secret: ${{ secrets.MYTESTSEC }}
       env: # Or as an environment variable
        super_secret: ${{ secrets.MYTESTSEC }
